name: ClypCore
version: ${project.version}
main: d.studio.test.Core
api-version: 1.16
authors: [ DaniCraftingYT ]
commands:
  fly:
    description: Permite volar
  gmc:
    description: Enable creative mode
    aliases:
      - gamemode_1
      - gmc
  gms:
    description: Enable survival mode
    aliases:
      - gamemode_0
      - gms
  gmsp:
    description: Enable spectator mode
    aliases:
      - gamemode_3
      - gmsp
  vanish:
    description: Enable vanish
    aliases:
      - v
  core-reload:
    description: Reload the plugin
  broadcast:
    description: Send a message to all lobbby's players
    aliases:
      - bc
      - announcement
  scoreboard-disable:
    description: Remove scoreboard
  gui:
    description: gui test